version: '3.8'

services:
  frontend: 
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  backend:
    build: /.backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - parser
    volumes:
      - ./backend:/app
    environment:
      DB_HOST:db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: budgetdb
      PARSER_URL: http://parser:6000
    
  parser:
    build: ./parser
    ports:
      - "6000:6000"
    volumes:
      - ./parser:/app

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: budgetdb
    ports:
      - "3306:3306"
    volumes:
      - db_data: /var/lib/mysql

volumes:
  db_data:
